# Generated by Django 5.1.1 on 2024-09-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
