# Generated by Django 5.1.1 on 2024-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('descricao', models.TextField(max_length=200)),
                ('codigo', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='estoque',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo',
            field=models.CharField(default='A definir', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='disponibilidade',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length=200),
        ),
    ]
