# Generated by Django 5.1.1 on 2024-09-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_categorias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
