# Generated by Django 5.1.1 on 2024-09-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_rename_categorias_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='escolaridade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(default='A definir', verbose_name=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='A definir', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='A definir', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
